name: Calc days

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *" # Täglich um 6:00 Uhr
    - cron: "0 12 * * *" # Täglich um 12:00 Uhr
    - cron: "0 22 * * *" # Täglich um 22:00 Uhr

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.4

      - name: Build and generate HTML
        env:
          SMASHRUN_API_TOKEN: ${{ secrets.SMASHRUN_API_TOKEN }}
        run: go run main.go

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
