name: Calc days

on:
  push:
    branches:
      - main # oder der Branch, der deinen Code hostet

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Erlaubt Lese- und Schreibzugriff auf Repository-Inhalte
      pages: write # Erforderlich für das Deployment auf GitHub Pages
      id-token: write # Optional: Erforderlich für OIDC-Token (z. B. für Cloud-Authentifizierung)

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Build and generate HTML
        run: go run main.go

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
